language: java
jdk: openjdk11

os:
  - linux
  - windows

script:
  - mvn verify
  - tail -200 target/it/basic/build.log

before_cache:
  - mvn build-helper:remove-project-artifact

cache:
  directories:
    - $HOME/.m2
